name: Docker Image CI # Actions名称

on: # 执行时机
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定 job 任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: checkout # 步骤名字
        # 使用 action 库 actions/checkout 拉取源码
        uses: actions/checkout@master

      # 安装依赖
      - name: install
        run: npm install

      # 打包
      - name: build project
        run: npm run build

        # SSH 登录服务器执行脚本
      - name: ssh login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # 使用 Git Bash 在 Windows 上运行脚本
          script:  d:/App/Git/bin/bash.exe -c 'pwd; cd d:/website-serve; ./website-serve.sh; ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}' 
      
